nseNames = ["DLF.NS", "JINDALSTEL.NS", "SUZLON.NS", "HDIL.NS", "IBREALEST.NS", "SBIN.NS", "ASHOKLEY.NS", "RCOM.NS",
            "HINDALCO.NS", "VEDL.NS", "HCC.NS", "SAIL.NS", "GMRINFRA.NS", "TATASTEEL.NS", "ICICIBANK.NS", "PNB.NS",
            "AXISBANK.NS", "UNIONBANK.NS", "IFCI.NS", "SUBEX.NS", "DISHTV.NS", "MEP.NS", "ITC.NS", "ADANIENT.NS",
            "SUNPHARMA.NS", "RPOWER.NS", "IDEA.NS", "JISLJALEQS.NS", "IDFC.NS", "JKTYRE.NS", "GLENMARK.NS",
            "YESBANK.NS", "IRB.NS", "JYOTISTRUC.NS", "CANBK.NS", "IDBI.NS", "IBULHSGFIN.NS", "SINTEX.NS",
            "BANKINDIA.NS", "MIRZAINT.NS", "NCC.NS", "CIPLA.NS", "NHPC.NS", "NITINFIRE.NS", "UCOBANK.NS", "SUNTV.NS",
            "BHEL.NS", "MARKSANS.NS", "PUNJLLOYD.NS", "COALINDIA.NS", "SCI.NS", "RELIANCE.NS", "INDHOTEL.NS",
            "ORIENTBANK.NS", "ANANTRAJ.NS", "MOTHERSUMI.NS", "STRTECH.NS", "ALBK.NS", "INDIACEM.NS", "HCL-INSYS.NS",
            "JUBILANT.NS", "INFY.NS", "ONGC.NS", "HFCL.NS", "BPCL.NS", "SOUTHBANK.NS", "HDFC.NS", "VOLTAS.NS",
            "TECHM.NS", "INFRATEL.NS", "PFC.NS", "JSWENERGY.NS", "PRAJIND.NS", "IOC.NS", "RELINFRA.NS", "APOLLOTYRE.NS",
            "SYNDIBANK.NS", "TATAPOWER.NS", "AMTEKAUTO.NS", "NMDC.NS", "IOB.NS", "INTELLECT.NS", "RAIN.NS",
            "VAKRANGEE.NS", "GHCL.NS", "ARVIND.NS"]  # 86

bseNames = ["MANAPPURAM.BO", "SUBEX.BO", "OPTOCIRCUI.BO", "SPICEJET.BO", "SUZLON.BO", "VAKRANGEE.BO", "PRAJIND.BO",
            "PNB.BO", "GMRINFRA.BO", "FSL.BO", "DLF.BO", "IFCI.BO", "RENUKA.BO", "RCOM.BO", "SBIN.BO", "HFCL.BO",
            "KUSHAL.BO", "AKSHOPTFBR.BO", "BAJAJHIND.BO", "BHEL.BO", "HCIL.BO", "MTNL.BO", "IDFC.BO", "FCEL.BO",
            "IBREALEST.BO", "DCW.BO", "BANKINDIA.BO", "NOCIL.BO", "JINDALSTEL.BO", "ALBK.BO", "FEDERALBNK.BO",
            "SINTEX.BO", "RANASUG.BO", "TREEHOUSE.BO", "CENTRUM.BO", "BSLIMITED.BO", "BANKBARODA.BO", "VEDL.BO",
            "IBVENTURES.BO", "ORIENTBANK.BO", "HDIL.BO", "SOUTHBANK.BO", "ONGC.BO", "IDBI.BO", "ADANIPOWER.BO",
            "GINNIFILA.BO", "ASHOKLEY.BO", "SYNDIBANK.BO", "HINDALCO.BO", "TATACOFFEE.BO", "SUNTECK.BO", "KMSUGAR.BO",
            "IOB.BO", "TATAMOTORS.BO", "RTNPOWER.BO", "STOREONE.BO", "SREINFRA.BO", "ITC.BO", "ICICIBANK.BO", "MGL.BO",
            "DBREALTY.BO", "EQUITAS.BO", "UNIONBANK.BO", "UJJIVAN.BO", "DELTACORP.BO", "IDFCBANK.BO",
            "UDAICEMENT.BO", "ANDHRABANK.BO", "DENABANK.BO", "BALRAMCHIN.BO", "MEGH.BO", "LIQUIDBEES.BO", "HCC.BO",
            "TV18BRDCST.BO", "VIJAYABANK.BO", "AMTEKAUTO.BO", "BODALCHEM.BO", "TATAMETALI.BO", "JINDALSAW.BO",
            "BOMDYEING.BO", "SAIL.BO", "ESSDEE.BO", "HARRMALAYA.BO", "RECLTD.BO", "INDIANACRY.BO", "DISHTV.BO",
            "IDEA.BO", "NHPC.BO", "ADANIPORTS.BO", "ANANTRAJ.BO", "GATI.BO", "CANBK.BO", "SREERAYA.BO", "USHAMART.BO",
            "RDEL.BO", "JISLJALEQS.BO", "STAMPEDE.BO", "TRIVENI.BO", "ESCORTS.BO"]  # 99
            
# "L&amp;TFH.BO" removed from bseNames
